language: elixir
elixir:
  - 1.3.0
otp_release:
  - 18.0
sudo: false
services:
  - postgresql
before_script:
  - cp config/travis_ci.exs config/config.exs
  - mix deps.get --only test
script:
  - mix test
